name: Build Container

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: "startsWith(github.ref, 'refs/tags/v')"
        name: build container (release)
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/deltalaboratory/go-imageserver:latest
            ghcr.io/deltalaboratory/go-imageserver:${{ github.ref_name }}
            ghcr.io/deltalaboratory/go-imageserver:${{ github.sha }}
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        name: build container (development)
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/deltalaboratory/go-imageserver:development
            ghcr.io/deltalaboratory/go-imageserver:${{ github.sha }}